/*export const ventes_flash = [
  {
    "id": 433,
    "slug": "l-arginine-300g-biotech-usa",
    "designation_fr": "L-ARGININE 300G - BIOTECH USA",
    "cover": "produits/January2025/kit8zH1SaSaSJUey8pBq.webp",
    "new_product": "0",
    "best_seller": "0",
    "note": 5,
    "alt_cover": null,
    "description_cover": null,
    "prix": 160,
    "pack": "0",
    "promo": 129,
    "promo_expiration_date": "2025-08-21 12:29:00"
  },
  {
    "id": 452,
    "slug": "pre-workout-advanced-420g-gold-standard",
    "designation_fr": "PRE WORKOUT ADVANCED 420G GOLD STANDARD",
    "cover": "produits/April2025/Xpps6iTOedjTAqg0z2nv.webp",
    "new_product": "0",
    "best_seller": "0",
    "note": 5,
    "alt_cover": "Pré-Workout Advanced 420g Gold Standard – Booster d'énergie pour musculation et performance – Disponible sur Protein.tn",
    "description_cover": "Découvrez le Pre Workout Advanced 420g de Gold Standard sur Protein.tn. Ce booster pré-entraînement ultra-concentré augmente l’énergie, la concentration et les performances physiques. Idéal pour les séances intenses de musculation ou de crossfit. Livraison rapide en Tunisie.",
    "prix": 180,
    "pack": "0",
    "promo": 159,
    "promo_expiration_date": "2025-08-21 12:28:00"
  },
  {
    "id": 454,
    "slug": "test-hd-elite-120-caps",
    "designation_fr": "TEST HD ÉLITE 120 CAPS",
    "cover": "produits/April2025/60vAY5f9F9LHZCzqebnK.webp",
    "new_product": "0",
    "best_seller": "0",
    "note": 5,
    "alt_cover": "TEST HD ÉLITE 120 CAPS Muscletech – Booster naturel de testostérone pour la force, la masse et l'énergie masculine",
    "description_cover": "TEST HD ÉLITE 120 CAPS de Muscletech est un booster naturel de testostérone conçu pour améliorer la force, la masse musculaire et les performances physiques. Idéal pour les hommes actifs et les pratiquants de musculation. Disponible sur Protein.tn avec livraison rapide en Tunisie.",
    "prix": 180,
    "pack": "0",
    "promo": 149,
    "promo_expiration_date": "2025-08-21 12:30:00"
  },
  {
    "id": 460,
    "slug": "bcaa-defender-kevin-levrone",
    "designation_fr": "BCAA DEFENDER - KEVIN LEVRONE",
    "cover": "produits/May2025/p5UMx3HnHyOhvi0kcqUn.webp",
    "new_product": "0",
    "best_seller": "0",
    "note": 5,
    "alt_cover": "alt=\"BCAA Defender Kevin Levrone – Acides aminés BCAA 8:1:1 pour la récupération et la performance\"",
    "description_cover": "BCAA Defender de Kevin Levrone associe un ratio 8:1:1 de BCAA avec glutamine, taurine et citrulline malate pour booster la récupération et la performance musculaire.",
    "prix": 140,
    "pack": "0",
    "promo": 109,
    "promo_expiration_date": "2025-08-21 12:30:00"
  }
];*/